# Dockerfile initially generated by ChatGPT.

# Use a base image with a compatible environment
FROM ubuntu:24.10

# Install dependencies: build essentials, CMake, COBOL compiler, and libraries
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    gnucobol \
    libmicrohttpd-dev \
    libcurl4-gnutls-dev \
    libcjson-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory to /app
WORKDIR /app

# Copy the entire source code into the container
COPY build.sh .
COPY CMakeLists.txt .
COPY pollen-rss.cob .
COPY http http/.
COPY json json/.

# Run the build script
RUN ./build.sh clean
RUN ./build.sh

# Expose port 8888 (as per your request)
EXPOSE 8888

# Run the binary produced by the build (adjust for your binary path)
CMD ["./build/bin/pollen-rss"]

