// Generated by ChatGPT
#include <stdio.h>
#include <string.h>

// Fortran subroutine declaration
void get_prevair_pollutant_data(
    const char date_str[8],
    float* target_lat,
    float* target_lon,
    int* max_pollutants,
    int* pollutant_count,
    char pollutant_names[][5],
    float* pollutant_averages,
    int* pollutant_indices
);

int main() {
    const char date_str[8] = "20250718";
    float lat = 48.0f;
    float lon = 2.5f;
    int max_pollutants = 10;
    int pollutant_count = 0;

    char pollutant_names[10][5];     // max_pollutants × 3-char strings
    float pollutant_averages[10];    // max_pollutants floats
    int pollutant_indices[10];        // max_pollutants integers

    get_prevair_pollutant_data(
        date_str,
        &lat,
        &lon,
        &max_pollutants,
        &pollutant_count,
        pollutant_names,
        pollutant_averages,
        pollutant_indices
    );

    printf("Received %d pollutants:\n", pollutant_count);
    for (int i = 0; i < pollutant_count; ++i) {
        printf("%.*s: %.3f (%d)\n", 4,
            pollutant_names[i],
            pollutant_averages[i],
            pollutant_indices[i]
        );
    }

    return 0;
}

