name: Run tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
    test:
      runs-on: ubuntu-latest
      permissions:
        checks: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Bats and bats libs
          id: setup-bats
          uses: bats-core/bats-action@3.0.0

        - name: Prepare reports directory
          run: mkdir -p reports

        - name: Run tests
          run: bats test/scenarios --recursive --formatter junit > reports/junit.xml

        - name: Publish Test Report
          uses: mikepenz/action-junit-report@v4
          if: always() # always run even if the previous step fails
          with:
            report_paths: 'reports/junit.xml'

        - name: Archive reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: reports
            path: reports

        - name: Archive logs
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: logs
            path: logs

